# Generated by Django 5.2.7 on 2025-10-27 14:51

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DispatchLogs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_id', models.IntegerField()),
                ('task_id', models.UUIDField(default=uuid.uuid4)),
                ('parent_id', models.IntegerField(blank=True, null=True)),
                ('request_created_at', models.DateTimeField(auto_now_add=True)),
                ('request_updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
